/** Durable Orbit state and decision vocabulary. */
export const ORBIT_SCHEMA_VERSION = 2;
export const COMMANDER_SOFT_DEADLINE_MS = 6 * 60_000;
export const COMMANDER_EXTENSION_MS = 4 * 60_000;
export const COMMANDER_HARD_CEILING_MS = 14 * 60_000;
export const EXECUTOR_TIMEOUT_MS = 8 * 60_000;
export const WATCHDOG_TIMEOUT_MS = 2 * 60_000;
export const GUARD_ESCALATION_THRESHOLD = 3;
export const GUARD_RECOVERY_CAP = 4;
export const MAX_CORRECTION_DEPTH = 2;
export const MAX_WATCHDOG_CALLS_PER_STEP = 2;
export const MAX_EXECUTOR_INTERRUPT_RETRIES = 2;
export const MAX_PLAN_STEPS = 5;
export const MIN_PLAN_STEPS = 1;
export const GUARD_FIRST_INSTRUCTION = 'Use a safer method and continue the current task. Do not retry the same blocked operation unchanged.';
export const GUARD_REPEAT_INSTRUCTION = 'The same blocked operation was attempted again. Stop repeating it and choose a different safe approach.';
export const GUARD_RETRY_INSTRUCTION = 'The previous approach repeatedly hit Orbit safety guards. Use a different safe approach. Do not retry the blocked operation.';
export const GUARD_NEEDS_USER_INSTRUCTION = 'This restricted action appears necessary for the user goal. Orbit has paused for user guidance.';
export const DEFAULT_CAPABILITIES = ['browser', 'web-api-recon'];
